# Generated by Django 3.1.7 on 2021-06-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catogeory',
            new_name='category',
        ),
    ]
