# Generated by Django 3.2.3 on 2021-06-08 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_auther_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catogeory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category'),
        ),
    ]
