# Generated by Django 3.2.3 on 2021-06-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210611_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
