# Generated by Django 3.1.7 on 2021-06-21 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210621_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catogeory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category'),
        ),
    ]
