# Generated by Django 3.1.7 on 2021-06-21 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210621_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catogeory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
