# Generated by Django 3.1.7 on 2021-06-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210621_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commnent',
            name='post',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='catogeory',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Commnent',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
