# Generated by Django 3.1.7 on 2021-06-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_category_commnent_contact_myuser_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
